### ISSUE TITLE
what are the season names?

### ISSUE THREAD

**Issue by ghost** [xelA/nft#1]
so i was messing a bit with the API, and I put seed 5878, and it gave me a Christmas season, so what other seasons are there?

**Comment by ghost** [comment]
ok after like 3 minutes i found that there are only 6 atm, ill close now

**Comment by AlexFlipnote** [comment]
Winter, Spring, Summer, Autumn, Norway, Halloween, Christmas

(Why Norway? I'm Norwegian and the national day is 17. May, so I added it for fun lol)
