### ISSUE TITLE
Seed doesn't have to conform to sha256 to be valid

### ISSUE THREAD

**Issue by ghost** [xelA/nft#5]
I'm fairly certain that there aren't underscores in a sha256 hash.

Reproducible example:
<code>a self-hosted instance of the code</code>/nft?seed=ah_shit_here_we_go_again

I get that this isn't serious and probably won't be worked on, I was just messing about with the code and found this, thinking it was funny.

**Comment by ghost** [comment]
Closing this issue, I was able to reach the creator of the Python code and it turned out to be a naming issue.
My bad 😅

**Comment by AlexFlipnote** [comment]
:heart:
